### ISSUE TITLE
Squeezeseg-Pytorch

### ISSUE THREAD

**Issue by lunw1024** [BenjaminYoung29/LeetCode#1]
I'm also trying to find a PyTorch implementation of squeezeseg
Your Squeezeseg-Pytorch has some errors. After I fixed that the loss wouldn't decrease.
Do you have any ideas? How can I reach out to you?

**Comment by BenjaminYoung29** [comment]
Hi,  my email is csbenjamin@mail.scut.edu.cn. 
Sorry that I can't help you with the problem. First of all it has been a long time that I've forgotten the detail of that work. Secondly I gave up that codes and turned to other networks that have pytorch version open source. I recommend you to refer to [his work](https://github.com/PRBonn/lidar-bonnetal).
